feat: Add each-assertions.
thenativeweb/assertthat pull request #408
Opened 2022-01-24 11:24 UTC by yeldiRium

- feat: Update dependencies.
- fix: Set, map, array and result are no longer treated as just objects.
- chore: Make error handling more precise.
- fix: AssertIsNotTrue/IsNotFalse now work with things that are neither true nor false.
- feat: Add each-assertions.

2022-01-25 04:39 UTC, goloroden requested changes
Just two super-small issues in the documentation (oh, and: I think we need to update the `LICENSE.txt` file to 2022, don't we?)

2022-01-25 04:39 UTC, goloroden commented on README.md
> +## Asserting on the contents of arrays, sets and saps
```suggestion
## Asserting on the contents of arrays, sets, and maps
```

2022-01-25 04:39 UTC, goloroden commented on README.md
> +It is possible to run the same assertion on all values in an array, set or map:
```suggestion
It is possible to run the same assertion on all values in an array, set, or map:
```

2022-02-10 13:59 UTC, goloroden approved these changes

2022-02-10 14:00 UTC, goloroden commented
@yeldiRium Basically, I'm fine with this 👍
Had you seen my comment regarding the date in the license file?

Besides that, from my POV, we're good to go 😊

2022-02-10 14:57 UTC, yeldiRium commented
@goloroden I've seen it now and bumped the year to 2022 :)

2022-02-10 15:43 UTC, goloroden submitted a review, later dismissed

2022-02-10 15:44 UTC, goloroden commented
@yeldiRium Thanks 😊

From my side, this is fine. I've approved the PR, but didn't want to merge it, because I did not know whether you wanted to also have feedback from someone else.

If you are fine with this, please feel free to merge. 😊

2022-02-22 08:16 UTC, strangedev requested changes
Implementation wise, there's just one small thing. Regarding the API, I have my concerns, please see below.

Maybe changing the API as described in my comment will improve the type safety, too?

2022-02-22 08:16 UTC, strangedev commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
I'm not sure if this would cause major troubles for the implementation you already did and I think I should have spoken out sooner, but I'm not completely on board with the way the new API reads.

At the moment, the assertions can be read fluently, i.e. "assert that X is Y". The way the new API is phrased, the assertions don't produce correct sentences anymore, e.g. "assert that X each is Y" is not a correct sentence.

I thought about other ways we could phrase the API and my idea is as follows:

```ts
assert.that.eachElementOf(arrayMapOrSet).is.somePredicate(...);
```

Let me know what you think :slightly_smiling_face:

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/CombinedAssertions.ts
> +              // eslint-disable-next-line @typescript-eslint/ban-types
I'm not sure the `Function` type is appropriate here, as it also matches `class` declarations, which are not strictly speaking callable, at least not without `new`. Maybe we could use something like `(...args: any[]) => any` instead?

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/assertActualIsInstanceOf.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-types
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/assertActualIsThrowing.ts
> +/* eslint-disable @typescript-eslint/ban-types */
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/assertActualIsThrowingAsync.ts
> +/* eslint-disable @typescript-eslint/ban-types */
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/assertions.ts
> +// This is where type safety goes to die. I hate this file.
What is the problem with this file? Also, can we remove this comment? :sweat_smile:

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/negated/assertActualIsNotThrowing.ts
> +/* eslint-disable @typescript-eslint/ban-types */
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/negated/assertActualIsNotInstanceOf.ts
> +  // eslint-disable-next-line @typescript-eslint/ban-types
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on lib/assertions/combined/negated/assertActualIsNotThrowingAsync.ts
> +/* eslint-disable @typescript-eslint/ban-types */
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 08:16 UTC, strangedev commented on test/unit/wrapAssertionForIterableTests.ts
> +      // eslint-disable-next-line @typescript-eslint/ban-types
See my comment in `lib/assertions/combined/CombinedAssertions.ts`.

2022-02-22 09:25 UTC, yeldiRium commented on lib/assertions/combined/CombinedAssertions.ts
> +              // eslint-disable-next-line @typescript-eslint/ban-types
Huh, I did not realize that. That makes sense. Implemented in [192171a](https://github.com/thenativeweb/assertthat/pull/408/commits/192171aee8b81111f18570f6262b728ed2c6b995)

2022-02-22 09:31 UTC, strangedev commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
I think that `assert.that(arreyMapOrSet).is.each.somePredicate(...);` sounds a bit funny, because the first part "assert that ..." reads like a statement of fact, while the rest "... is each Y" reads like a question.

2022-02-22 09:32 UTC, yeldiRium commented on lib/assertions/combined/assertions.ts
> +// This is where type safety goes to die. I hate this file.
Is removed.

In this file _all_ assertions exist and no inference on what assertions are available is possible from the `actual` parameter. In this file it is impossible to check whether all functions that are defined in the outside-presenting API are present or correct, since during runtime all assertions must exist but at compile time only a subset should exist, depending on the function parameter. So at some point we have to betray the compiler and I don't like it. But it works.

2022-02-22 09:32 UTC, strangedev commented on lib/assertions/combined/assertions.ts
> +// This is where type safety goes to die. I hate this file.
I see, that's unfortunate.

2022-02-22 09:34 UTC, yeldiRium commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
true

2022-02-22 09:35 UTC, strangedev commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
RFC @goloroden @dotKuro

2022-02-22 09:38 UTC, strangedev commented on test/unit/wrapAssertionForIterableTests.ts
> +      // eslint-disable-next-line @typescript-eslint/no-extra-parens
Curious, but fine with me.

2022-02-22 10:53 UTC, dotKuro commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
I had the same concerns as @strangedev  when proposing this API. I would also prefer the `eachElementOf` approach, but if it just too much work, I would also agree with the current implementation.

2022-02-22 19:30 UTC, goloroden commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
Hey everone 👋 

Sorry for the late reply, I didn't make it before.
Actually, although I'm also very sad to have caused unneeded work, I agree that

`assert.that.eachElementOf(...).is.xyz()`

reads way better than the current approach. Of course it's more work to change this now than to leave it, but I'd prefer to invest the work once and then be happy every time I use the API, then save some time now, and every time I use the API think "had we changed it back then" … 😉

So, from my side, I'd say, let's do the change to the more fluently reading version.

2022-03-22 09:34 UTC, strangedev submitted a review, later dismissed

2022-03-22 09:35 UTC, strangedev commented
Awesome :heart_eyes:

2022-03-22 10:19 UTC, dotKuro submitted a review, later dismissed

2022-03-22 10:19 UTC, goloroden requested changes
@yeldiRium The changes look really great 👍 

However, the documentation is not yet up-to-date (although this is just a small change). Could you please adjust this?

2022-03-22 10:19 UTC, goloroden commented on README.md
> +assert.that(arrayOfStrings).each.is.startingWith('foo');
The new API is not yet reflected in the documentation here.

2022-03-22 10:19 UTC, goloroden commented on README.md
> +While the `.each.is...` assertions run the assertion on each item of arrays and sets, it runs the assertions only on the values of maps.
… or here 😉

2022-03-22 11:57 UTC, goloroden approved these changes

2022-03-22 12:00 UTC, merged